import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "@/styles/globals.css";
import { NavBar } from "@/components/Navigation/NavBar";
import { Footer } from "@/components/Footer";
import { getAuthServerSession } from "@/utils/authOptions";
import { Provider } from "@/components/Provider";
import { PopUpProvider } from "@/components/PopUp/PopUpContext";
import MessagePopUp from "@/components/PopUp/MessagePopUp";
import ErrorPopup from "@/components/PopUp/ErrorPopUp";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getAuthServerSession();

  return (
    <html lang="fr">
      <body
        className={`${montserrat.variable} antialiased`}
      >
        <Provider session={session}>
          <PopUpProvider>
            <div className="fixed z-[250] bottom-4 right-4 flex gap-5 flex-col">
              <MessagePopUp />
              <ErrorPopup />
            </div>
            <NavBar />
            {children}
            <Footer />
          </PopUpProvider>
        </Provider>
      </body>
    </html>
  );
}
